### ISSUE TITLE
Wrong Positions for Specific Effects

### ISSUE THREAD

**Issue by LifeDreamer24** [punteroo/TF2-Item-Plugins#2] opened 2021-02-28 14:41 UTC
**Bug Description**
Some of the unusual effects aren't in the right place. Which are either attached too low, (on the neck / under the head) or even on the waist (rotating around the torso or so)...

**To Reproduce**
1. Enter 'sm_unu' or any command to bring up the menu.
2. Equip yourself a specific hat. (on my side i tried the 'Antarctic Eyewear' or the 'Bat Hat' which made the bug)
3. Select the 'Circling TF Logo' if you have the 'Bat Hat' or the 'Divine Desire' if you equipped the 'Antarctic Eyewear'.

**Additional Notes**
Thoses bugs can sometimes happen with simillar effects e.g. 'Subatomic' or 'Atomic' for the neck bug but i did not found some effects that cause the bug related to the waist bug with the 'Circling TF Logo'.

**Screenshots**
![bugreport1](https://user-images.githubusercontent.com/62817314/109422040-e1d0f800-79a7-11eb-972e-63c143c810c2.png)
![bugreport2](https://user-images.githubusercontent.com/62817314/109422041-e2698e80-79a7-11eb-9de6-73d062c2158a.png)

Hope this can help/be useful.
/Simon ;)

**Comment by punteroo** [comment] 2021-03-02 17:54
Hello, thank you for reporting this issue!

This happens because of certain hats' equip region. The engine just doesn't know which bone the effect must be attached to, so it does this. I'll try to implement a fix where players would be able to "adjust" their unusual effects' height just like if you were inside the loadout tab, and probably implement some sort of validation system to automatically re-attach the effect (will take quite some time to research).

I'll mark this issue and keep you updated on progress. If resolved, I'll push a new release.

**Comment by punteroo** [comment] 2021-03-02 18:44
Performed some tests on my real Unusual hat and attributes that control the effects' position are ``particle_effect_use_head_origin`` and ``particle_effect_vertical_offset`` (IDs 520 and 519 respectively).

I'll try to implement these on the Unusuals plugin for a dynamic fix.

**Comment by punteroo** [comment] 2021-03-02 18:53
Confirmed to be malfunctioning with **The Bat Hat**

![Wrong Position](https://i.imgur.com/mR49HFS.png)

**Comment by punteroo** [comment] 2021-03-04 00:25
This has been fixed on the latest [v2.3.2 release](https://github.com/punteroo/TF2-Item-Plugins/releases/tag/v2.3.2).

Thanks for reporting this issue! I'll close it now.

**Closed as completed by punteroo** 2021-03-04 00:25 UTC
Labels: bug, fixed
